import { Post } from "@/types/post";

export async function getPosts(
  boardKey: string,
  threadIndex: number,
): Promise<Post[]> {
  return [
    {
      id: 1,
      postOrder: 1,
      author: "작성자1",
      idcode: "abc123",
      content: "첫 번째 게시물입니다.",
      rawContent: "첫 번째 게시물입니다.",
      contentType: "text",
      createdAt: new Date(),
      updatedAt: new Date(),
      threadId: 1,
      userId: 1,
      contentUpdatedAt: new Date(),
      imageUrl: null,
      isAutoPost: false,
      isEdited: false,
      isHidden: false,
    },
    {
      id: 2,
      postOrder: 2,
      author: "작성자2",
      idcode: "def456",
      content: "두 번째 게시물입니다.",
      rawContent: "두 번째 게시물입니다.",
      contentType: "text",
      createdAt: new Date(),
      updatedAt: new Date(),
      threadId: 1,
      userId: 1,
      contentUpdatedAt: new Date(),
      imageUrl: null,
      isAutoPost: false,
      isEdited: false,
      isHidden: false,
    },
    {
      id: 3,
      postOrder: 3,
      author: "작성자3",
      idcode: "ghi789",
      content: "세 번째 게시물입니다.",
      rawContent: "세 번째 게시물입니다.",
      contentType: "text",
      createdAt: new Date(),
      updatedAt: new Date(),
      threadId: 1,
      userId: 1,
      contentUpdatedAt: new Date(),
      imageUrl: null,
      isAutoPost: false,
      isEdited: false,
      isHidden: false,
    },
    {
      id: 4,
      postOrder: 4,
      author: "작성자4",
      idcode: "jkl012",
      content: "네 번째 게시물입니다.",
      rawContent: "네 번째 게시물입니다.",
      contentType: "text",
      createdAt: new Date(),
      updatedAt: new Date(),
      threadId: 1,
      userId: 1,
      contentUpdatedAt: new Date(),
      imageUrl: null,
      isAutoPost: false,
      isEdited: false,
      isHidden: false,
    },
    {
        id: 5,
        postOrder: 5,
        author: "작성자5",
        idcode: "mno345",
        content: "다섯 번째 게시물입니다.",
        rawContent: "다섯 번째 게시물입니다.",
        contentType: "text",
        createdAt: new Date(),
        updatedAt: new Date(),
        threadId: 1,
        userId: 1,
        contentUpdatedAt: new Date(),
        imageUrl: null,
        isAutoPost: false,
        isEdited: false,
        isHidden: false,
    },
    {
        id: 6,
        postOrder: 6,
        author: "작성자6",
        idcode: "pqr678",
        content: "여섯 번째 게시물입니다.",
        rawContent: "여섯 번째 게시물입니다.",
        contentType: "text",
        createdAt: new Date(),
        updatedAt: new Date(),
        threadId: 1,
        userId: 1,
        contentUpdatedAt: new Date(),
        imageUrl: null,
        isAutoPost: false,
        isEdited: false,
        isHidden: false,
    },
    {
        id: 7,
        postOrder: 7,
        author: "작성자7",
        idcode: "stu901",
        content: "일곱 번째 게시물입니다.",
        rawContent: "일곱 번째 게시물입니다.",
        contentType: "text",
        createdAt: new Date(),
        updatedAt: new Date(),
        threadId: 1,
        userId: 1,
        contentUpdatedAt: new Date(),
        imageUrl: null,
        isAutoPost: false,
        isEdited: false,
        isHidden: false,
    },
    {
        id: 8,
        postOrder: 8,
        author: "작성자8",
        idcode: "vwx234",
        content: "여덟 번째 게시물입니다.",
        rawContent: "여덟 번째 게시물입니다.",
        contentType: "text",
        createdAt: new Date(),
        updatedAt: new Date(),
        threadId: 1,
        userId: 1,
        contentUpdatedAt: new Date(),
        imageUrl: null,
        isAutoPost: false,
        isEdited: false,
        isHidden: false,
    },
  ];
}
